import 'package:flutter/material.dart';


Widget styledContainer(Widget child) {
  return Container(
    margin: EdgeInsets.symmetric(vertical: 6),
    decoration: BoxDecoration(
      color: Color(0xFF282A36),
      borderRadius: BorderRadius.circular(14),
    ),
    padding: EdgeInsets.all(16),
    child: child,
  );
}




Widget code1(){
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_entity.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Product ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'String ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'name;\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'double ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'price;\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '{', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'required this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '.', style: TextStyle(color: Color(0xFFF8F8F2))), 
          TextSpan(text: 'name, ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'required this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '.', style: TextStyle(color: Color(0xFFF8F8F2))), 
          TextSpan(text: 'price', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code2(){
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_validator.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductValidator ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '? ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'validateName', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '      if ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: '.isEmpty', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  return ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: "'Nome não pode ser vazio'", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '      return null', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   }\n\n', style: TextStyle(color: Color(0xFFFF79C6))),
          

          TextSpan(text: '   String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '? ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'validatePrice', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '      final', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' value', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' = ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'double', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'tryParse', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '      if ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'value', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' == null || ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'value', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' <= ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '0', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  return ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: "'Preço inválido'", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '      return null', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    }\n', style: TextStyle(color: Color(0xFFFF79C6))),

          TextSpan(text: '}', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code3(){
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_repository.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductRepository ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'List', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '> _products', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' = []', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '   void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'addProduct', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' product', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '      _products.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'add', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'product', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   }\n\n', style: TextStyle(color: Color(0xFFFF79C6))),

          TextSpan(text: '   List', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '>', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '  getAll', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '() =>', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' _products;\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code4() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_type.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'abstract ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductType ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   String ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'get ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'label;\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ElectronicProduct ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'extends ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductType ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   String ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'get ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'label ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '=> ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: "'Eletrônico';\n", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'FoodProduct ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'extends ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductType ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   String ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'get ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'label ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '=> ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: "'Alimento';\n", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '}\n', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code5() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_card.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductCard ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'extends ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'StatelessWidget ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '   final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Product ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'product;\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '   final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductType ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'type;\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),


          TextSpan(text: '   const ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductCard', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '{', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'required this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '.product, ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'required this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '.type', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),


          TextSpan(text: '   @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   Widget ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'build', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'BuildContext', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' context', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ') {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '      return ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ListTile', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))), 
          TextSpan(text: '(\n', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))), 

          TextSpan(text: '        title', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Text', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: 'product.name', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '        subtitle', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Text', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '\'\$', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '{', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: "type.label", style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ' - R', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '\\\$', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '\$', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '{', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: 'product.price.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'toStringAsFixed', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: '2', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: '}', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: '\'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '      )', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))), 
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   }\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '}', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}



Widget code6() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: 'void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'showProductType', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'ProductType ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' type', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ') {\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    print', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: "'Tipo: \$", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '{', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'type', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: '.label', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: "'", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '// Funciona com qualquer subtipo de ProductType\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'showProductType', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'ElectronicProduct', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ');\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'showProductType', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'FoodProduct', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ');\n', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code7() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: 'abstract ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Displayable ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'display', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: 'abstract ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Updatable ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'update', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'double', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductService ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'implements ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Displayable', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Updatable ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    Product ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' _product;\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    ProductService', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '._product', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'display', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '() {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '        print', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: "'Produto: \$", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '{', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '_product.name', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ", Preço: \$", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '{', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '_product.price', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: "'", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    }\n\n', style: TextStyle(color: Color(0xFFFF79C6))),

          TextSpan(text: '    @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'update', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'double', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color(0xFFFF79C6))),

          TextSpan(text: '        _product = ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    }\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '}', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code8() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: 'abstract ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'IProductRepository ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'addProduct', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Product ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'product', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))), 

          TextSpan(text: '     List', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '>', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '  getAll', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'LocalProductRepository ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'implements ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'IProductRepository ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '   final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'List', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '> _products', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' = []', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'addProduct', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Product ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'product', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' => ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_products.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'add', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'product', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    List', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '>', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '  getAll', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '() =>', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' _products;\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}\n', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code9() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_controller.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductController ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '  final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'IProductRepository ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'repository;\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '  ProductController', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '.repository', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '  void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'saveProduct', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'String', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'double', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '  price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '      final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'product = ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'Product', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'name', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'price', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '      repository.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'addProduct', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'product', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   }\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '}\n', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}


Widget code10() {
  return styledContainer(
    RichText(
      text: TextSpan(
        style: TextStyle(fontFamily: 'monospace', fontSize: 15, color: Color(0xFFF8F8F2)),
        children: [
          TextSpan(text: '// product_form.dart\n', style: TextStyle(color: Color(0xFF6272A4))),
          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductForm ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'extends ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'StatefulWidget ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '{\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductController ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'controller;\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    const ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductForm', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '{', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'required this', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '.controller', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '}', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    State', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'ProductForm', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '>', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '  createState', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '() => ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_ProductFormState', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '}\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: 'class ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_ProductFormState ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'extends ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'State', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '<', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'ProductForm', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '>', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_nameController', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' = ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'TextEditingController', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_priceController', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' = ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'TextEditingController', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '    final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_validator', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' = ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'ProductValidator', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '()', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),


          TextSpan(text: '    void ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_submit', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '() {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '        final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'nameError = ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '_validator.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'validateName', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '_nameController.text', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '        final ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'priceError = ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '_validator.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'validatePrice', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '_priceController.text', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n\n', style: TextStyle(color: Color(0xFFF8F8F2))),


          TextSpan(text: '        if ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'nameError', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' == null && ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'priceError', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' == null', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ') {\n', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),

          TextSpan(text: '            widget.controller.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'saveProduct(\n', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '                 _nameController.text,\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '                 double.', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'parse', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: '_priceController.text', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '            )', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '            ScaffoldMessenger', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'of(', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: 'context', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ')', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '.', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'showSnackBar(\n', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '                 SnackBar', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: 'context', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Text', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: "'Produto salvo com sucesso!'", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ",\n", style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '            )', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '       } ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' else ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' {\n', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),

          TextSpan(text: '          showDialog(\n', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '              context', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' context,\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '              builder', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: '_', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ' => ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'AlertDialog', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(\n', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: "                 title", style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' Text', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: "'Erro'", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: "                 content", style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: ' Text', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),

          TextSpan(text: "'\$", style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text:'{nameError', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' ?? \' \'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '} ', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text:'\$', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text:'{priceError', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ' ?? \' \'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: '} ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '\'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '              )', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '          )', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '       }\n', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '    }\n\n', style: TextStyle(color: Color(0xFFFF79C6))),


          TextSpan(text: '    @override\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '    Widget ', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: 'build', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: '(', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'BuildContext', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ' context', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ') {\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '        return ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Column(\n', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '            children', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '[ \n', style: TextStyle(color: Color(0xFF50FA7B))),

          TextSpan(text: '                TextField', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: 'controller', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_nameController', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'decoration', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'InputDecoration', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(labelText', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '\'Nome\'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),

          TextSpan(text: '                TextField', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: 'controller', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_priceController', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'decoration', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'InputDecoration', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(labelText', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '\'Preço\'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),


          TextSpan(text: '                ElevatedButton', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: 'onPressed', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '_submit', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ', ', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: 'child', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ': ', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: 'Text', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: '(', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: '\'Salvar\'', style: TextStyle(color: Color.fromARGB(255, 248, 250, 118))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 255, 137, 2))),
          TextSpan(text: ')', style: TextStyle(color: Color.fromARGB(255, 153, 0, 255))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '            ]', style: TextStyle(color: Color(0xFF50FA7B))),
          TextSpan(text: ',\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '       )', style: TextStyle(color: Color.fromARGB(255, 2, 238, 255))),
          TextSpan(text: ';\n', style: TextStyle(color: Color(0xFFF8F8F2))),
          TextSpan(text: '   }\n', style: TextStyle(color: Color(0xFFFF79C6))),
          TextSpan(text: '}\n', style: TextStyle(color: Color(0xFFF8F8F2))),
        ],
      ),
    ),
  );
}